// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/integrations/ssrfGuard.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * SSRF guard for outbound fetches driven by user-supplied URLs -- specifically
 * brightspace-sync's `icsUrl`, the one place in this product where a server-side
 * fetch target comes directly from user input rather than a hardcoded API domain
 * (WHOOP/RescueTime always fetch a known, fixed API host). Without this, a user could
 * point `icsUrl` at an internal service, a cloud metadata endpoint
 * (`169.254.169.254`), or `localhost`/`host.docker.internal`, and the Edge Function
 * would make that request with server-side network access on their behalf.
 *
 * Pure IP/hostname classification, no I/O -- DNS resolution itself (real I/O) happens
 * in the Deno-side wrapper that calls this; the pure function is what's actually
 * exhaustively testable offline.
 *
 * Known limitation, documented rather than silently assumed away: checking the
 * resolved IP at request time reduces but does not eliminate DNS-rebinding risk (an
 * attacker's DNS could resolve to a public IP at check time and a private one at the
 * actual connection). A fully hardened fix would pin the checked IP for the connection
 * itself (a custom fetch dispatcher), which is real additional infrastructure --
 * flagged as a follow-up, not built here, since the practical attacker model for a
 * personal single-user app's calendar-sync feature is low relative to that cost.
 */

const BLOCKED_HOSTNAMES = new Set(['localhost', 'host.docker.internal', 'metadata.google.internal']);

function ipv4ToInt(ip: string): number | null {
  const parts = ip.split('.').map(Number);
  if (parts.length !== 4 || parts.some((p) => Number.isNaN(p) || p < 0 || p > 255)) return null;
  return ((parts[0]! << 24) | (parts[1]! << 16) | (parts[2]! << 8) | parts[3]!) >>> 0;
}

function inIpv4Range(ip: string, base: string, prefixLength: number): boolean {
  const ipInt = ipv4ToInt(ip);
  const baseInt = ipv4ToInt(base);
  if (ipInt == null || baseInt == null) return false;
  const mask = prefixLength === 0 ? 0 : (0xffffffff << (32 - prefixLength)) >>> 0;
  return (ipInt & mask) === (baseInt & mask);
}

const IPV4_PRIVATE_RANGES: Array<[string, number]> = [
  ['10.0.0.0', 8], // RFC1918
  ['172.16.0.0', 12], // RFC1918
  ['192.168.0.0', 16], // RFC1918
  ['127.0.0.0', 8], // loopback
  ['169.254.0.0', 16], // link-local -- includes the AWS/GCP/Azure metadata address, 169.254.169.254
  ['0.0.0.0', 8], // "this network"
  ['100.64.0.0', 10], // carrier-grade NAT (RFC6598)
];

/** True for any IPv4 or IPv6 address that is loopback, link-local, unique-local, or
 *  otherwise not routable on the public internet -- the set of addresses a server-side
 *  fetch must never be allowed to silently reach on a user's say-so. */
export function isPrivateOrReservedIp(ip: string): boolean {
  const normalized = ip.trim().toLowerCase();

  if (normalized.includes(':')) {
    // IPv6: loopback (::1), unique-local (fc00::/7), link-local (fe80::/10),
    // IPv4-mapped addresses re-checked against the IPv4 ranges above.
    if (normalized === '::1' || normalized === '::') return true;
    if (/^f[cd][0-9a-f]{2}:/.test(normalized)) return true; // fc00::/7
    if (/^fe[89ab][0-9a-f]:/.test(normalized)) return true; // fe80::/10
    const ipv4Mapped = normalized.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/);
    if (ipv4Mapped) return isPrivateOrReservedIp(ipv4Mapped[1]!);
    return false;
  }

  return IPV4_PRIVATE_RANGES.some(([base, prefix]) => inIpv4Range(normalized, base, prefix));
}

export interface UrlSafetyCheck {
  ok: boolean;
  reason: string | null;
}

/** The part of the check that doesn't need DNS resolution -- scheme and a hardcoded
 *  hostname blocklist. Always run before attempting resolution. */
export function checkUrlSchemeAndHostname(rawUrl: string): UrlSafetyCheck {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    return { ok: false, reason: 'Not a valid URL.' };
  }
  if (url.protocol !== 'https:') {
    return { ok: false, reason: 'Only https:// URLs are allowed.' };
  }
  if (BLOCKED_HOSTNAMES.has(url.hostname.toLowerCase())) {
    return { ok: false, reason: `Host "${url.hostname}" is not allowed.` };
  }
  return { ok: true, reason: null };
}
