// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/grades/letterGrade.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

export interface GradeBoundary {
  letter: string;
  minPct: number;
}

/** Inclusive lower bounds, highest match wins — DOMAIN_ENGINE_SPEC.md §2. */
export function letterGradeForPct(pct: number, boundaries: GradeBoundary[]): string {
  if (boundaries.length === 0) {
    throw new Error('letterGradeForPct requires at least one grade boundary');
  }
  const sorted = [...boundaries].sort((a, b) => b.minPct - a.minPct);
  const match = sorted.find((b) => pct >= b.minPct);
  return (match ?? sorted[sorted.length - 1]!).letter;
}
