// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/learn/ingestionTargets.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * How many lessons a source should yield, and how few of them are enough to start.
 *
 * Both numbers are pure arithmetic over a page count, so they live here rather than in the edge
 * function that consumes them — law 2 of this codebase, and the reason `supabase/functions/_shared/
 * learn/types.ts` re-exports these instead of owning a second copy.
 *
 * They are also two instances of one bug, which is why they sit together: **a fixed number applied
 * to a variable-sized book is always wrong at one end.** ULM's spec originally floored the lesson
 * count at 30, which forced a 40-page book to pad itself with weak candidates to hit a number; the
 * same repo then shipped a fixed threshold of 10 carded lessons before a book could be called
 * `partial`, which structurally excluded every book whose target count never reached 10 —
 * including its own onboarding sample book, the one user progressive availability exists for. Both
 * are fixed here by scaling.
 */

/**
 * Target density from the brief: ~1 lesson per 8–10 pages. 9 is the midpoint; the floor and the cap
 * are the real guarantees.
 */
export const PAGES_PER_LESSON = 9;
export const LESSON_FLOOR = 20;
export const LESSON_CAP = 60;

/**
 * ~1 lesson per 8–10 pages, floored and capped — computed, never asked of the model (D9).
 *
 * A source with no known page count gets the floor: the honest minimum, not a guess scaled from
 * nothing.
 */
export function targetLessonCount(pageCount: number | null): number {
  if (pageCount == null || pageCount <= 0) return LESSON_FLOOR;
  const scaled = Math.round(pageCount / PAGES_PER_LESSON);
  return Math.min(LESSON_CAP, Math.max(LESSON_FLOOR, scaled));
}

/** Ceiling on the partial threshold: enough cards for a real first session on a large source. */
export const PARTIAL_THRESHOLD_CEILING = 10;
/** Floor on the partial threshold: still a warm-up-sized deck, not a teaser. */
export const PARTIAL_THRESHOLD_FLOOR = 3;

/**
 * How many carded lessons make a source usable before its ingestion has finished — the point at
 * which "start learning now" is an honest offer rather than a button onto an empty queue.
 *
 * Half the target, floored at 3 and capped at 10. Scaled rather than fixed for the reason in the
 * file header: a fixed 10 means any source targeting fewer than 10 lessons can never pass through
 * `partial` at all, which silently turns progressive availability off for exactly the short
 * sources it helps most.
 *
 * `ceiling` and `floor` are parameters rather than constants baked into the body so a caller with a
 * different session length can state its own — and so the test suite can pin the shape of the
 * formula independently of today's numbers.
 */
export function computePartialThreshold(
  targetCount: number,
  ceiling: number = PARTIAL_THRESHOLD_CEILING,
  floor: number = PARTIAL_THRESHOLD_FLOOR,
): number {
  return Math.min(ceiling, Math.max(floor, Math.ceil(targetCount / 2)));
}
