// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/interventions/staleTaskPrompt.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

import type { LocalDate } from '../types.ts';
import { daysBetween } from '../util/date.ts';

/**
 * The stale-task surface (FOLLOWUPS.md S5): recoveryMode.ts's overdueTaskCount is
 * correctly windowed to 7 days (an unbounded count would make Recovery Mode permanent
 * once a few tasks were abandoned), but that means a task older than 7 days stops
 * counting toward anything AND isn't surfaced anywhere else -- the product silently
 * accumulates dead tasks, the same "nothing the system defers is silent" violation this
 * whole intervention layer exists to prevent. This is the honest disclosure Recovery
 * Mode's windowing needed a companion for: "these have been sitting three weeks --
 * still real, or should they go?"
 *
 * Deliberately a distinct, LARGER threshold than Recovery Mode's 7-day window -- this
 * isn't "you're falling behind this week" (Recovery Mode's job), it's "this has been
 * abandoned long enough that pretending it's still an active plan is itself the lie."
 */

export const STALE_TASK_PROMPT_ACTIONS = ['Still real', 'Let it go'] as const;
export type StaleTaskPromptAction = (typeof STALE_TASK_PROMPT_ACTIONS)[number];

export interface StaleTaskCheckInput {
  today: LocalDate;
  plannedDate: LocalDate;
  taskTitle: string;
  /** Days since planned_date before a task counts as stale. Default 21 ("three weeks"),
   *  the Lead's own example -- deliberately well beyond Recovery Mode's 7-day near-term
   *  window, since this answers a different question. */
  thresholdDays?: number;
}

export interface StaleTaskDecision {
  shouldFire: boolean;
  reason: string | null;
  daysSincePlanned: number;
}

const DEFAULT_STALE_TASK_THRESHOLD_DAYS = 21;

export function evaluateStaleTaskPrompt(input: StaleTaskCheckInput): StaleTaskDecision {
  const thresholdDays = input.thresholdDays ?? DEFAULT_STALE_TASK_THRESHOLD_DAYS;
  const daysSincePlanned = Math.max(daysBetween(input.plannedDate, input.today), 0);
  const shouldFire = daysSincePlanned >= thresholdDays;
  if (!shouldFire) return { shouldFire: false, reason: null, daysSincePlanned };

  return {
    shouldFire: true,
    reason: `"${input.taskTitle}" has been sitting for ${daysSincePlanned} days -- still real, or should it go?`,
    daysSincePlanned,
  };
}
