// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/retrieval/queue.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

import type { LocalDate } from '../types.ts';
import { compareLocalDate } from '../util/date.ts';
import { computeSchedulerState, type AttemptEntry, type SchedulerState } from './scheduler.ts';

/**
 * The daily due queue -- BLUEPRINT 5.4/5.5. Draws across every course by due date, so
 * interleaving comes free rather than being a feature: review is mixed by default
 * because due dates from different courses naturally interleave, and equal-date ties are
 * dealt round-robin across courses so a big backlog in one course cannot monopolize the
 * front of the queue.
 */

export interface QueueQuestion {
  questionId: number;
  courseId: number;
  topic: string | null;
  createdDate: LocalDate;
  attempts: AttemptEntry[];
}

export interface QueueItem {
  questionId: number;
  courseId: number;
  topic: string | null;
  state: SchedulerState;
  /** True when this question's topic is calibration-flagged (sure-but-wrong) -- these
   *  order FIRST, which is the whole of "weight those topics up": deterministic and
   *  explainable, not a hidden multiplier. */
  weighted: boolean;
}

export function buildDueQueue(
  questions: QueueQuestion[],
  today: LocalDate,
  weightedTopics: ReadonlySet<string> = new Set(),
): QueueItem[] {
  const due = questions
    .map((q) => ({
      questionId: q.questionId,
      courseId: q.courseId,
      topic: q.topic,
      state: computeSchedulerState(q.attempts, q.createdDate),
      weighted: q.topic != null && weightedTopics.has(q.topic),
    }))
    .filter((item) => compareLocalDate(item.state.dueDate, today) <= 0);

  // Sort: weighted topics first, then by due date (most overdue first). Round-robin
  // across courses breaks remaining ties so interleaving survives equal dates.
  due.sort((a, b) => {
    if (a.weighted !== b.weighted) return a.weighted ? -1 : 1;
    const dateCmp = compareLocalDate(a.state.dueDate, b.state.dueDate);
    if (dateCmp !== 0) return dateCmp;
    return a.questionId - b.questionId; // stable pre-order for the round-robin pass
  });

  return roundRobinWithinTies(due);
}

/** Within each (weighted, dueDate) bucket, deal one question per course in turn. */
function roundRobinWithinTies(items: QueueItem[]): QueueItem[] {
  const result: QueueItem[] = [];
  let i = 0;
  while (i < items.length) {
    let j = i;
    while (
      j < items.length &&
      items[j]!.weighted === items[i]!.weighted &&
      items[j]!.state.dueDate === items[i]!.state.dueDate
    ) {
      j++;
    }
    const bucket = items.slice(i, j);
    const byCourse = new Map<number, QueueItem[]>();
    for (const item of bucket) {
      const list = byCourse.get(item.courseId) ?? [];
      list.push(item);
      byCourse.set(item.courseId, list);
    }
    const lanes = [...byCourse.values()];
    let dealt = 0;
    let round = 0;
    while (dealt < bucket.length) {
      for (const lane of lanes) {
        const item = lane[round];
        if (item != null) {
          result.push(item);
          dealt++;
        }
      }
      round++;
    }
    i = j;
  }
  return result;
}
