// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/workload/recoveryAdjustment.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

const RED_BOUNDARY = 33;
const YELLOW_BOUNDARY = 67;
const GREEN_CEILING = 100;

const RED_ADJUSTMENT = 0.75;
const YELLOW_ADJUSTMENT = 1.0;
const GREEN_ADJUSTMENT = 1.1;

function lerp(x: number, x0: number, x1: number, y0: number, y1: number): number {
  return y0 + ((x - x0) / (x1 - x0)) * (y1 - y0);
}

/**
 * Maps a WHOOP recovery percentage to the [0.75, 1.10] capacity adjustment from
 * DOMAIN_ENGINE_SPEC.md §7, anchored to WHOOP's own red/yellow/green bands (Lead ruling,
 * L5) rather than an arbitrary linear scale: recovery 33 -> 0.75, 67 -> 1.00, 100 -> 1.10,
 * linear *between* anchors. Anchoring to the bands the user already sees in WHOOP keeps
 * the adjustment legible ("why did green cut my capacity?" should never be a fair
 * question). Deliberately linear rather than a step function at the boundaries: a step
 * creates a cliff a user could game by nudging recovery across a threshold, which is
 * exactly the kind of excuse-generating incentive this product must not create.
 */
export function recoveryAdjustmentFromWhoopPct(whoopRecoveryPct: number | null): number {
  if (whoopRecoveryPct == null) return 1.0;
  if (whoopRecoveryPct <= RED_BOUNDARY) return RED_ADJUSTMENT;
  if (whoopRecoveryPct >= GREEN_CEILING) return GREEN_ADJUSTMENT;
  if (whoopRecoveryPct <= YELLOW_BOUNDARY) {
    return lerp(whoopRecoveryPct, RED_BOUNDARY, YELLOW_BOUNDARY, RED_ADJUSTMENT, YELLOW_ADJUSTMENT);
  }
  return lerp(whoopRecoveryPct, YELLOW_BOUNDARY, GREEN_CEILING, YELLOW_ADJUSTMENT, GREEN_ADJUSTMENT);
}
