// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/cards/rotation.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * The End-of-Hour card rotation -- BLUEPRINT Part III and IV-C.
 *
 * The course's ritual is to re-read your goals, motivation and thought habits at the end of
 * every hour. This compresses that into three cards, and rotation is what stops it becoming
 * wallpaper: the same three cards every hour would be read once and skipped forever, so the
 * variability IS the mechanism, not a flourish.
 */

/**
 * `enemy` joins the set with D50: the End-of-Hour rotation can occasionally show what you are
 * running FROM alongside what you are running toward. It is an ordinary card type — same weighting,
 * same rotation, no special handling — because a card that always appeared would stop being read,
 * which is the exact failure the rotation exists to prevent.
 */
export type CardType = 'goal' | 'motivation' | 'thought_habit' | 'trait' | 'tenx' | 'enemy';

export interface RotationCard {
  id: number;
  type: CardType;
  text: string;
  /** Relative likelihood. 0 means "never show", without deleting the card. */
  weight: number;
}

/**
 * One card from each slot, in the blueprint's order: a Goal, a Motivation item, and a
 * Thought Habit **or** 2.0 Trait (they share the third slot).
 *
 * The 10X card is deliberately not in any slot -- the blueprint describes it as a single
 * static card, so it is held in the library for display elsewhere rather than competing for
 * a rotation seat every hour.
 */
const SLOTS: CardType[][] = [['goal'], ['motivation'], ['thought_habit', 'trait']];

/**
 * Weighted pick from one group.
 *
 * `random` is injected rather than calling Math.random directly so rotation is testable --
 * a function that cannot be pinned cannot be asserted on, and "it looked random" is not a
 * test. Cards with weight 0 are excluded rather than being given a vanishing chance.
 */
function pickWeighted(cards: RotationCard[], random: () => number): RotationCard | null {
  const eligible = cards.filter((c) => c.weight > 0);
  if (eligible.length === 0) return null;

  const total = eligible.reduce((sum, c) => sum + c.weight, 0);
  let threshold = random() * total;
  for (const card of eligible) {
    threshold -= card.weight;
    if (threshold <= 0) return card;
  }
  // Floating-point drift on the final comparison; the last eligible card is the answer.
  return eligible[eligible.length - 1] ?? null;
}

/**
 * Picks the rotation for one End-of-Hour.
 *
 * Returns fewer than three cards when a slot's library is empty, rather than padding with a
 * card from another slot or inventing placeholder text. An empty library is a real state --
 * a new user has one -- and the honest response is a shorter rotation, not filler that
 * looks like content the user wrote.
 */
export function pickRotation(cards: RotationCard[], random: () => number = Math.random): RotationCard[] {
  const picked: RotationCard[] = [];
  for (const slotTypes of SLOTS) {
    const candidates = cards.filter((c) => slotTypes.includes(c.type));
    const choice = pickWeighted(candidates, random);
    if (choice != null) picked.push(choice);
  }
  return picked;
}
