// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/backplan/phaseTemplates.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

export type DeliverableType =
  | 'paper'
  | 'report'
  | 'problem_set'
  | 'exam'
  | 'project'
  | 'reading'
  | 'quiz'
  | 'post'
  | 'admin';

export interface PhaseTemplateEntry {
  name: string;
  /** Fraction of total effort, as a share of 1.0. */
  fraction: number;
  /**
   * The phase that actually produces/submits the artifact. Never droppable by the crash
   * plan and reserved before any other phase — a plan that quietly omits submitting the
   * work is not a legitimate compression. DOMAIN_ENGINE_SPEC.md §4, amended per Lead review.
   */
  required?: boolean;
}

const PAPER_PHASES: PhaseTemplateEntry[] = [
  { name: 'understand', fraction: 0.1 },
  { name: 'sources', fraction: 0.2 },
  { name: 'outline', fraction: 0.1 },
  { name: 'draft', fraction: 0.3 },
  { name: 'revise', fraction: 0.2 },
  { name: 'final', fraction: 0.1, required: true },
];

/** Exam plans favor retrieval practice over re-reading notes — per the brief. */
const EXAM_PHASES: PhaseTemplateEntry[] = [
  { name: 'inventory', fraction: 0.1 },
  { name: 'concept pass', fraction: 0.25 },
  { name: 'retrieval practice', fraction: 0.4 },
  { name: 'weak-spot pass', fraction: 0.2 },
  { name: 'light review', fraction: 0.05 },
];

export const PHASE_TEMPLATES: Record<DeliverableType, PhaseTemplateEntry[]> = {
  paper: PAPER_PHASES,
  report: PAPER_PHASES,
  problem_set: [
    { name: 'understand', fraction: 0.15 },
    { name: 'attempt', fraction: 0.5 },
    { name: 'stuck-review', fraction: 0.2 },
    { name: 'check', fraction: 0.15, required: true },
  ],
  exam: EXAM_PHASES, // no artifact is submitted -> no required phase
  project: [
    { name: 'scope', fraction: 0.1 },
    { name: 'build', fraction: 0.45 },
    { name: 'integrate', fraction: 0.2 },
    { name: 'test', fraction: 0.15 },
    { name: 'finalize', fraction: 0.1, required: true },
  ],
  reading: [
    { name: 'survey', fraction: 0.15 },
    { name: 'read', fraction: 0.6 },
    { name: 'notes', fraction: 0.25 },
  ],
  // BLUEPRINT 5.3 puts quiz in the exam row: same retrieval-first planning, smaller scale.
  // The scale difference is carried by estimated_minutes, not by a different shape.
  quiz: EXAM_PHASES,
  post: [
    { name: 'compose', fraction: 0.7 },
    { name: 'revise and post', fraction: 0.3, required: true },
  ],
  // Admin work has no meaningful decomposition -- pretending it has phases would be
  // template theater. One required phase: it is done or it is not.
  admin: [{ name: 'complete', fraction: 1, required: true }],
};
