// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/signal/allocation.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * Signal:Noise — the coverage axis.
 *
 * Ported from LifeOS (`lib/checkins/allocation.ts`, `lib/business/sn-ratio.ts`) with two rulings
 * layered on top, both recorded as decisions rather than invented here.
 *
 * **D38 — what counts as Signal is per-user.** His code compiles `Signal = Deen + Business` into
 * the metric. That is one person's ranking of their own life, and three people use this app; a
 * student's School hours are not semi-noise. The signal set is data on the profile, defaulting to
 * all five domains, which makes the ratio mean what the directive says it means: coverage, i.e.
 * where all the time went, with unaccounted time as the only noise.
 *
 * **D33 — the confession stays.** The bite of this metric is having to look at two hours and admit
 * where they went. A window may be PRE-FILLED only from something that already carries its own
 * evidence — a completed Hour has a deliverable and a domain, a logged prayer has a time. Every
 * other gap is presented as an explicit question about visible time, never silently absorbed,
 * defaulted, or rounded away. Coverage counts confessions, not inferences.
 *
 * His noise split is kept verbatim because it is right: noise is always reported as
 * otherCommitments vs wasted, never as one total. A heavy school week and a lost afternoon both
 * land on the noise side and are nothing alike, and collapsing them would make a legitimate
 * trade-off indistinguishable from a leak — which would quietly pressure someone to skip the gym
 * to look better on paper.
 */

import { LIFE_DOMAINS, type LifeDomain } from '../domains/domains.ts';

/** Minutes a single allocation window covers. Comes from `profiles.checkin_interval_minutes`. */
export const DEFAULT_WINDOW_MINUTES = 120;

/** Drag/step granularity. */
export const STEP_MINUTES = 15;

/**
 * A press on a domain still at zero creates this rather than doing nothing: a bar segment at zero
 * renders at zero width, so there was never a draggable target to grab. Deliberately not `STEP` —
 * it is a one-time "start here" tap, not a drag increment.
 */
export const STARTER_BLOCK_MINUTES = 5;

export type Allocation = Record<LifeDomain, number>;

export function emptyAllocation(): Allocation {
  return Object.fromEntries(LIFE_DOMAINS.map((d) => [d, 0])) as Allocation;
}

function assignedMinutes(allocation: Allocation): number {
  return LIFE_DOMAINS.reduce((sum, d) => sum + (allocation[d] || 0), 0);
}

/**
 * What is left of the window once every domain is subtracted.
 *
 * Derived, never an input. That single choice is what makes "no operation can take minutes from
 * another domain" fall out of the model instead of needing to be enforced separately — and it is
 * why unaccounted time cannot be hidden by editing a number.
 */
export function wastedMinutes(allocation: Allocation, windowMinutes = DEFAULT_WINDOW_MINUTES): number {
  return Math.max(0, windowMinutes - assignedMinutes(allocation));
}

/** Adds one step, or whatever is left. A full window is a no-op, not an error. */
export function increment(
  allocation: Allocation,
  domain: LifeDomain,
  windowMinutes = DEFAULT_WINDOW_MINUTES,
): Allocation {
  const free = wastedMinutes(allocation, windowMinutes);
  if (free === 0) return allocation;
  return { ...allocation, [domain]: allocation[domain] + Math.min(STEP_MINUTES, free) };
}

/** Subtracts one step, floored at zero. Freed minutes return to unaccounted. */
export function decrement(allocation: Allocation, domain: LifeDomain): Allocation {
  if (allocation[domain] === 0) return allocation;
  return { ...allocation, [domain]: allocation[domain] - Math.min(STEP_MINUTES, allocation[domain]) };
}

/**
 * Drag entry point: snap to the nearest step, then clamp to the domain's own minutes plus the free
 * pool.
 *
 * The NaN guard is his and is kept for his reason: a drag handler derives `requested` from pointer
 * position over element width, and a width of zero (not yet laid out, hidden breakpoint,
 * mid-transition) is a divide-by-zero. Every clamp below passes NaN through silently, which would
 * corrupt this domain's value permanently. Infinity is deliberately NOT guarded — it clamps
 * correctly through the same arithmetic.
 */
export function setMinutes(
  allocation: Allocation,
  domain: LifeDomain,
  requested: number,
  windowMinutes = DEFAULT_WINDOW_MINUTES,
): Allocation {
  const snapped = Math.round(requested / STEP_MINUTES) * STEP_MINUTES;
  if (Number.isNaN(snapped)) return allocation;
  const ceiling = allocation[domain] + wastedMinutes(allocation, windowMinutes);
  return { ...allocation, [domain]: Math.min(Math.max(snapped, 0), ceiling) };
}

// ---------------------------------------------------------------------------
// The ratio
// ---------------------------------------------------------------------------

export interface AllocationRow {
  domain: LifeDomain | 'wasted';
  minutes: number;
}

export interface SignalNoiseTotals {
  signalMinutes: number;
  /** otherCommitments + wasted. Reported alongside the split, never instead of it. */
  noiseMinutes: number;
  otherCommitmentsMinutes: number;
  wastedMinutes: number;
  /** Null when nothing has been accounted for at all -- never 0, which would read as total noise. */
  signalShare: number | null;
}

/**
 * Buckets accounted minutes into signal, other commitments, and unaccounted.
 *
 * An unrecognised domain string is ignored rather than folded into either side: a gap is better
 * than a miscounted total, and a silently mis-bucketed minute is a number nobody can audit.
 */
export function bucketAllocation(
  rows: AllocationRow[],
  signalDomains: readonly LifeDomain[],
): SignalNoiseTotals {
  const signal = new Set<string>(signalDomains);
  let signalMinutes = 0;
  let otherCommitmentsMinutes = 0;
  let wasted = 0;

  for (const row of rows) {
    const minutes = Math.max(0, row.minutes);
    if (row.domain === 'wasted') wasted += minutes;
    else if (signal.has(row.domain)) signalMinutes += minutes;
    else if ((LIFE_DOMAINS as readonly string[]).includes(row.domain)) otherCommitmentsMinutes += minutes;
  }

  const total = signalMinutes + otherCommitmentsMinutes + wasted;
  return {
    signalMinutes,
    noiseMinutes: otherCommitmentsMinutes + wasted,
    otherCommitmentsMinutes,
    wastedMinutes: wasted,
    signalShare: total === 0 ? null : signalMinutes / total,
  };
}

// ---------------------------------------------------------------------------
// Coverage -- D33's amendment, in code
// ---------------------------------------------------------------------------

/**
 * What a window can be at read time.
 *
 * `unknown` is the state that keeps the metric honest: a window whose answering period has passed
 * without an answer is not wasted and is not signal — it is simply unaccounted, and it is never
 * penalised. Deriving `wasted` from silence would let the app invent the very number a person is
 * supposed to confess.
 */
export type WindowState = 'upcoming' | 'open' | 'answered' | 'prefilled' | 'unknown';

export interface AllocationWindow {
  /** ISO instant the window starts. */
  start: string;
  /** ISO instant the window ends. */
  end: string;
  state: WindowState;
}

/**
 * How long after a window closes it can still be answered. After this it becomes `unknown`
 * permanently rather than converting to wasted.
 */
export const ANSWER_GRACE_MINUTES = 30;

/**
 * Evidence that can pre-fill a window without asking.
 *
 * D33 draws the line here and nowhere else: a source may pre-fill only if it already carries its
 * own account of the time. A completed Hour has a deliverable and a domain. A logged prayer has a
 * name and a window. A confirmed workout has sets. Anything else — an app being open, a guess from
 * a calendar entry, a rounded remainder — is inference, and inference is what turns this metric
 * into an activity log wearing its name.
 */
export interface EvidenceSpan {
  start: string;
  end: string;
  domain: LifeDomain;
  /** What makes this evidence rather than a guess. Shown to the user, so it must be specific. */
  source: string;
}

export interface CoverageSummary {
  totalWindows: number;
  /** Windows a person answered themselves. */
  confessed: number;
  /** Windows filled from evidence that carried its own account of the time. */
  prefilled: number;
  /** Windows whose answering period passed unanswered. Never counted against anyone. */
  unknown: number;
  /** Windows still open or not yet started. */
  pending: number;
  /**
   * Answered as a share of windows that could have been answered.
   *
   * Counts confessions and evidence, and EXCLUDES unknown from the denominator entirely rather
   * than scoring it as a miss -- a window nobody was asked about is not a failure to answer.
   * Null when no window has closed yet.
   */
  coverage: number | null;
}

export function summariseCoverage(windows: AllocationWindow[]): CoverageSummary {
  let confessed = 0;
  let prefilled = 0;
  let unknown = 0;
  let pending = 0;

  for (const window of windows) {
    if (window.state === 'answered') confessed += 1;
    else if (window.state === 'prefilled') prefilled += 1;
    else if (window.state === 'unknown') unknown += 1;
    else pending += 1;
  }

  const accountable = confessed + prefilled;
  return {
    totalWindows: windows.length,
    confessed,
    prefilled,
    unknown,
    pending,
    coverage: accountable === 0 && unknown === 0 ? null : accountable / (accountable + unknown),
  };
}

export interface UnaccountedGap {
  start: string;
  end: string;
  minutes: number;
}

/**
 * The gaps the Night Plan close-out asks about.
 *
 * This is the whole of Kareem's amendment to D33. Windows already covered by evidence are dropped
 * — we do not ask about time we have a deliverable for. Everything else that has closed and was
 * never answered is returned as a **visible span with a start and an end**, so the close-out can
 * say "2:00–4:00 is unaccounted" and ask. It is never absorbed, never defaulted to wasted, and
 * never quietly rounded into a neighbouring window.
 *
 * Returning an empty array means every closed window is accounted for — which is a real state and
 * a good one, and reads very differently from a screen with nothing on it.
 */
export function unaccountedGaps(
  windows: AllocationWindow[],
  evidence: EvidenceSpan[],
  now: Date,
): UnaccountedGap[] {
  const nowMs = now.getTime();
  const gaps: UnaccountedGap[] = [];

  for (const window of windows) {
    if (window.state === 'answered' || window.state === 'prefilled') continue;

    const startMs = Date.parse(window.start);
    const endMs = Date.parse(window.end);
    if (Number.isNaN(startMs) || Number.isNaN(endMs)) continue;
    // Only closed windows are asked about. An open one is still being lived.
    if (endMs > nowMs) continue;

    const covered = evidence.some((span) => {
      const evStart = Date.parse(span.start);
      const evEnd = Date.parse(span.end);
      if (Number.isNaN(evStart) || Number.isNaN(evEnd)) return false;
      // Any real overlap counts as evidence for this window. Partial overlap is deliberately
      // enough: the alternative is asking someone to re-account for an hour they already logged an
      // Hour inside, which is the friction that makes people stop answering at all.
      return evStart < endMs && evEnd > startMs;
    });
    if (covered) continue;

    gaps.push({
      start: window.start,
      end: window.end,
      minutes: Math.max(0, Math.round((endMs - startMs) / 60000)),
    });
  }

  return gaps;
}

/**
 * Resolves a window's state at read time. Nothing here is written, so a window is never marked
 * missed by a job that may or may not have run.
 */
export function resolveWindowState(
  window: { start: string; end: string },
  hasAnswer: boolean,
  evidence: EvidenceSpan[],
  now: Date,
): WindowState {
  if (hasAnswer) return 'answered';

  const startMs = Date.parse(window.start);
  const endMs = Date.parse(window.end);
  const nowMs = now.getTime();
  if (Number.isNaN(startMs) || Number.isNaN(endMs)) return 'unknown';

  const covered = evidence.some((span) => {
    const evStart = Date.parse(span.start);
    const evEnd = Date.parse(span.end);
    return !Number.isNaN(evStart) && !Number.isNaN(evEnd) && evStart < endMs && evEnd > startMs;
  });
  if (covered) return 'prefilled';

  if (nowMs < startMs) return 'upcoming';
  if (nowMs < endMs + ANSWER_GRACE_MINUTES * 60000) return 'open';
  return 'unknown';
}
