// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/util/math.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

export function clamp01(x: number): number {
  return Math.min(1, Math.max(0, x));
}
