// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/self/drift.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * Drift triggers and the confrontation they surface (D50).
 *
 * The source module's structure with its engine replaced. That document pairs a vision with a
 * "Hell" and uses shame to close the gap. This keeps the pairing and removes the shame, and the
 * removal is mechanical rather than editorial — five properties do the work, and four of them live
 * here:
 *
 * 1. **The app never judges.** Nothing in this file generates language about the user. It decides
 *    WHETHER to show something and WHICH dimension it belongs to. The words shown are always
 *    `dimension.driftStatement`, verbatim, written by the person reading them.
 * 2. **Rarity is the mechanism.** A daily confrontation is a notification people learn to dismiss;
 *    the point is that this almost never fires, so it lands when it does. The limiter is
 *    deliberately strict and is checked here rather than trusted to a caller.
 * 3. **Every confrontation carries its evidence.** A firing names the fact behind it — "that Hour
 *    ended with 9 distractions" — so the user can check it. An unexplained confrontation would be
 *    the app asserting something about someone rather than showing them their own record.
 * 4. **There is always a door.** `ConfrontationOffer` carries its two ways forward as data, so a
 *    surface cannot render the confrontation without them. Confrontation then path back — never
 *    confrontation alone.
 *
 * The fifth property, the per-dimension opt-out, is a column.
 */

import type { LocalDate } from '../types.ts';
import { addDays, compareLocalDate, daysBetween } from '../util/date.ts';

export type DriftTrigger =
  | 'distracted_hour'
  | 'abandoned_hour'
  | 'dimension_dormant'
  | 'mit_recrowned'
  | 'day_under_baseline';

export type DriftResponse = 'started_hour' | 'crowned_tomorrow' | 'dismissed';

/**
 * At most one confrontation per this many days.
 *
 * Not a constant chosen for tidiness. Once a day was the ceiling the owner set; three days is the
 * default because the mechanic's whole force is that it is rare, and something that fires every day
 * is a nag whose text people stop reading — which would destroy the one thing it has, namely that
 * the words are theirs.
 */
export const MIN_DAYS_BETWEEN_CONFRONTATIONS = 3;

/** A dimension must be genuinely quiet, not merely quiet this week, before dormancy fires. */
export const DORMANT_DAYS = 14;

/** Distractions in a single Hour past this is the pattern, not a bad hour. */
export const DISTRACTED_HOUR_THRESHOLD = 8;

/** An MIT crowned this many nights running and never finished. */
export const MIT_RECROWN_THRESHOLD = 3;

export interface DriftDimension {
  id: number;
  name: string;
  /** The user's own words. Null means this dimension cannot fire — nothing to show. */
  driftStatement: string | null;
  alertsEnabled: boolean;
  /** Local date of the most recent act routed here, or null if there has never been one. */
  lastActDate: LocalDate | null;
}

/** A candidate firing, before the limiter has had its say. */
export interface DriftSignal {
  trigger: DriftTrigger;
  dimensionId: number;
  /** The checkable fact, as a sentence fragment: "that Hour ended with 9 distractions". */
  evidence: string;
  /** Structured form of the same fact, stored so a later read can re-render it. */
  evidenceData: Record<string, number | string>;
}

export interface ConfrontationOffer {
  dimensionId: number;
  dimensionName: string;
  trigger: DriftTrigger;
  /** The user's own text. The app adds nothing to it and never paraphrases it. */
  statement: string;
  evidence: string;
  evidenceData: Record<string, number | string>;
  /**
   * The two ways forward. Present as DATA rather than left to a surface, so a confrontation
   * structurally cannot be rendered without its door.
   */
  doors: readonly ['start_hour', 'crown_tomorrow'];
}

export interface DriftInput {
  dimensions: DriftDimension[];
  signals: DriftSignal[];
  today: LocalDate;
  /** When anything last fired for this user, from `drift_events`. */
  lastConfrontationDate: LocalDate | null;
  /** Per-user master switch, from settings. */
  enabled: boolean;
}

/**
 * Decides whether to confront, and with what.
 *
 * Returns null far more often than not, and that is the design working rather than a gap. Every
 * gate below is a reason to stay quiet, and they are ordered cheapest-first so the common path is
 * a few comparisons.
 */
export function selectConfrontation(input: DriftInput): ConfrontationOffer | null {
  if (!input.enabled) return null;

  // The rate limit, checked here rather than trusted to a caller. A surface that forgot it would
  // turn the feature into the nag it exists not to be.
  if (input.lastConfrontationDate !== null) {
    const sinceLast = daysBetween(input.lastConfrontationDate, input.today);
    if (sinceLast < MIN_DAYS_BETWEEN_CONFRONTATIONS) return null;
  }

  const byId = new Map(input.dimensions.map((d) => [d.id, d]));

  for (const signal of input.signals) {
    const dimension = byId.get(signal.dimensionId);
    if (!dimension) continue;
    // No written statement means nothing to show. The statement IS the opt-in.
    if (!dimension.driftStatement || dimension.driftStatement.trim().length === 0) continue;
    if (!dimension.alertsEnabled) continue;

    return {
      dimensionId: dimension.id,
      dimensionName: dimension.name,
      trigger: signal.trigger,
      statement: dimension.driftStatement,
      evidence: signal.evidence,
      evidenceData: signal.evidenceData,
      doors: ['start_hour', 'crown_tomorrow'] as const,
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Detectors — each turns data we already have into a candidate signal
// ---------------------------------------------------------------------------

export interface HourFact {
  sessionId: number;
  dimensionId: number | null;
  distractions: number;
  status: 'completed' | 'abandoned';
  hasDeliverable: boolean;
  date: LocalDate;
}

/**
 * An Hour that went badly in one of two specific ways.
 *
 * Note what is NOT a trigger: a short Hour, a low-output Hour, an Hour on a bad day. Those are
 * ordinary and confronting someone over them would make the mechanic noise. Only two shapes fire —
 * a lot of distractions, and an Hour abandoned with nothing produced — because both are things the
 * person already knows about and would recognise.
 */
export function detectHourSignals(hours: HourFact[]): DriftSignal[] {
  const signals: DriftSignal[] = [];
  for (const hour of hours) {
    if (hour.dimensionId === null) continue;
    if (hour.distractions >= DISTRACTED_HOUR_THRESHOLD) {
      signals.push({
        trigger: 'distracted_hour',
        dimensionId: hour.dimensionId,
        evidence: `that Hour ended with ${hour.distractions} distractions`,
        evidenceData: { distractions: hour.distractions, sessionId: hour.sessionId },
      });
      continue;
    }
    if (hour.status === 'abandoned' && !hour.hasDeliverable) {
      signals.push({
        trigger: 'abandoned_hour',
        dimensionId: hour.dimensionId,
        evidence: 'that Hour ended without producing what it set out to',
        evidenceData: { sessionId: hour.sessionId },
      });
    }
  }
  return signals;
}

/**
 * A dimension nobody has fed in a fortnight.
 *
 * A dimension that has NEVER had an act does not fire. Someone who wrote a drift statement
 * yesterday and has not acted on it yet is at the beginning, not adrift — and confronting them on
 * day one would be the app punishing a person for starting.
 */
export function detectDormantDimensions(
  dimensions: DriftDimension[],
  today: LocalDate,
): DriftSignal[] {
  const cutoff = addDays(today, -DORMANT_DAYS);
  const signals: DriftSignal[] = [];
  for (const dimension of dimensions) {
    if (dimension.lastActDate === null) continue;
    if (compareLocalDate(dimension.lastActDate, cutoff) > 0) continue;
    const days = daysBetween(dimension.lastActDate, today);
    signals.push({
      trigger: 'dimension_dormant',
      dimensionId: dimension.id,
      evidence: `nothing has fed this in ${days} days`,
      evidenceData: { days, lastAct: dimension.lastActDate },
    });
  }
  return signals;
}

export interface MitFact {
  taskId: number;
  title: string;
  dimensionId: number | null;
  /** Consecutive nights this task was crowned MIT without being completed. */
  consecutiveCrownings: number;
}

/** The task you keep meaning to do. Named plainly, because the user already knows which one. */
export function detectRecrownedMits(mits: MitFact[]): DriftSignal[] {
  return mits
    .filter((m) => m.dimensionId !== null && m.consecutiveCrownings >= MIT_RECROWN_THRESHOLD)
    .map((m) => ({
      trigger: 'mit_recrowned' as const,
      dimensionId: m.dimensionId as number,
      evidence: `"${m.title}" has been tomorrow's most important thing ${m.consecutiveCrownings} nights running`,
      evidenceData: { taskId: m.taskId, nights: m.consecutiveCrownings },
    }));
}

export interface DayFact {
  date: LocalDate;
  hoursCompleted: number;
  baseline: number;
  /** The dimension the day's Hours mostly served, or null when they were spread or absent. */
  dimensionId: number | null;
}

/**
 * A day that closed under its own baseline.
 *
 * A baseline of zero never fires: a rest day the user themselves defined is not drift, and treating
 * it as such would punish someone for keeping their own schedule. This is the same rule the Day Won
 * calculation already follows.
 */
export function detectUnderBaselineDays(days: DayFact[]): DriftSignal[] {
  return days
    .filter((d) => d.baseline > 0 && d.hoursCompleted < d.baseline && d.dimensionId !== null)
    .map((d) => ({
      trigger: 'day_under_baseline' as const,
      dimensionId: d.dimensionId as number,
      evidence: `${d.hoursCompleted} of ${d.baseline} Hours on ${d.date}`,
      evidenceData: { completed: d.hoursCompleted, baseline: d.baseline, date: d.date },
    }));
}

/**
 * The label a surface puts above the evidence line.
 *
 * Deliberately flat and factual. There is no version of this that scolds, and there is no
 * adjective anywhere in it — the emotional weight is supposed to come entirely from the user's own
 * sentence underneath, which is the only thing in the feature allowed to carry any.
 */
export const TRIGGER_LABELS: Readonly<Record<DriftTrigger, string>> = {
  distracted_hour: 'You wrote this about Focus',
  abandoned_hour: 'You wrote this',
  dimension_dormant: 'You wrote this',
  mit_recrowned: 'You wrote this',
  day_under_baseline: 'You wrote this',
};
