// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/planning/freeIntervals.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * Free-time-interval detection against real calendar busy events, within a day's waking
 * window. Nothing in this codebase computes actual clock-time gaps yet -- capacity.ts's
 * `freeCalendarMinutes` is a single aggregate (waking minutes minus busy minutes), enough
 * to answer "how much capacity today" but not "which specific hours are actually open,"
 * which weekly planning's focus-block placement needs.
 *
 * Pure interval math: clip busy events to the window, merge overlapping/adjacent ones
 * (so a genuinely free gap is never split by a redundant boundary), then return what's
 * left between them.
 */

export interface TimeInterval {
  /** ISO instant. */
  start: string;
  /** ISO instant, strictly after start. */
  end: string;
}

export interface BusyEvent {
  startAt: string;
  endAt: string;
}

function clip(event: BusyEvent, windowStartMs: number, windowEndMs: number): { startMs: number; endMs: number } | null {
  const startMs = Math.max(new Date(event.startAt).getTime(), windowStartMs);
  const endMs = Math.min(new Date(event.endAt).getTime(), windowEndMs);
  if (endMs <= startMs) return null; // fully outside the window, or zero/negative duration
  return { startMs, endMs };
}

/** Merges overlapping and touching intervals (sorted ascending by start) into the
 *  minimal set of disjoint busy blocks. */
function mergeIntervals(clipped: Array<{ startMs: number; endMs: number }>): Array<{ startMs: number; endMs: number }> {
  const sorted = [...clipped].sort((a, b) => a.startMs - b.startMs);
  const merged: Array<{ startMs: number; endMs: number }> = [];
  for (const interval of sorted) {
    const last = merged[merged.length - 1];
    if (last && interval.startMs <= last.endMs) {
      last.endMs = Math.max(last.endMs, interval.endMs);
    } else {
      merged.push({ ...interval });
    }
  }
  return merged;
}

/**
 * `dayStart`/`dayEnd` bound the waking window to search within (e.g. 08:00-23:00 local,
 * already resolved to real instants by the caller -- this function does no timezone work
 * itself, same "pure, no I/O" boundary as the rest of packages/core). Busy events outside
 * the window, or with zero/negative duration after clipping, are silently excluded rather
 * than producing a degenerate interval.
 */
export function findFreeIntervals(dayStart: string, dayEnd: string, busyEvents: BusyEvent[]): TimeInterval[] {
  const windowStartMs = new Date(dayStart).getTime();
  const windowEndMs = new Date(dayEnd).getTime();
  if (windowEndMs <= windowStartMs) return [];

  const clipped = busyEvents
    .map((event) => clip(event, windowStartMs, windowEndMs))
    .filter((c): c is { startMs: number; endMs: number } => c !== null);
  const busy = mergeIntervals(clipped);

  const free: TimeInterval[] = [];
  let cursorMs = windowStartMs;
  for (const block of busy) {
    if (block.startMs > cursorMs) {
      free.push({ start: new Date(cursorMs).toISOString(), end: new Date(block.startMs).toISOString() });
    }
    cursorMs = Math.max(cursorMs, block.endMs);
  }
  if (cursorMs < windowEndMs) {
    free.push({ start: new Date(cursorMs).toISOString(), end: new Date(windowEndMs).toISOString() });
  }

  return free;
}

export function intervalMinutes(interval: TimeInterval): number {
  return (new Date(interval.end).getTime() - new Date(interval.start).getTime()) / 60_000;
}
