// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/planning/loadForecast.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

import type { LocalDate } from '../types.ts';
import { addDays } from '../util/date.ts';
import { baselineForWeekday, DEFAULT_BASELINE_HOURS } from '../hours/hours.ts';

/**
 * 3-week load forecast -- BLUEPRINT 5.5's "manager behavior": sum planned minutes per
 * day against the per-weekday baselines and name an overflow NOW, instead of letting
 * two exams collide into a Sunday-night discovery. Deterministic and explainable: same
 * inputs, same forecast, every number traceable to a planned item or a baseline.
 *
 * The caller aggregates planned minutes per day from whatever plans exist (backplan
 * milestones, weekly-plan blocks, exam-curve sessions); this function owns only the
 * comparison and the pull-earlier suggestion, so it never grows a data dependency.
 */

export const FORECAST_HORIZON_DAYS = 21;

export interface PlannedDayLoad {
  date: LocalDate;
  minutes: number;
}

export interface ForecastDay {
  date: LocalDate;
  plannedMinutes: number;
  baselineMinutes: number;
  /** Positive when the day is over its baseline. 0 otherwise -- never negative. */
  overflowMinutes: number;
}

export interface PullEarlierSuggestion {
  /** The overloaded day. */
  fromDate: LocalDate;
  /** The earliest day with spare capacity that could absorb some of it. */
  toDate: LocalDate;
  minutes: number;
}

export interface LoadForecast {
  days: ForecastDay[];
  /** Days over baseline, in date order -- the warnings. */
  overloadedDays: ForecastDay[];
  /** Greedy earliest-spare-capacity suggestions, capped at one per overloaded day. */
  suggestions: PullEarlierSuggestion[];
  totalPlannedMinutes: number;
  totalBaselineMinutes: number;
}

export function buildLoadForecast(
  today: LocalDate,
  planned: PlannedDayLoad[],
  weekdayBaselines: Record<string, unknown> | null | undefined,
  fallbackBaselineHours: number = DEFAULT_BASELINE_HOURS,
): LoadForecast {
  const plannedByDate = new Map<LocalDate, number>();
  for (const item of planned) {
    plannedByDate.set(item.date, (plannedByDate.get(item.date) ?? 0) + item.minutes);
  }

  const days: ForecastDay[] = [];
  for (let i = 0; i < FORECAST_HORIZON_DAYS; i++) {
    const date = addDays(today, i);
    const plannedMinutes = plannedByDate.get(date) ?? 0;
    const baselineMinutes = baselineForWeekday(weekdayBaselines, date, fallbackBaselineHours) * 60;
    days.push({
      date,
      plannedMinutes,
      baselineMinutes,
      overflowMinutes: Math.max(0, plannedMinutes - baselineMinutes),
    });
  }

  const overloadedDays = days.filter((d) => d.overflowMinutes > 0);

  // Greedy pull-earlier: for each overflow, the EARLIEST day before it with spare
  // capacity -- earlier is strictly better for spacing, and one suggestion per overflow
  // keeps the output an instrument reading, not a solver's opaque reshuffle.
  const spare = days.map((d) => Math.max(0, d.baselineMinutes - d.plannedMinutes));
  const suggestions: PullEarlierSuggestion[] = [];
  for (const overloaded of overloadedDays) {
    const overloadedIndex = days.findIndex((d) => d.date === overloaded.date);
    for (let i = 0; i < overloadedIndex; i++) {
      const spareHere = spare[i]!;
      if (spareHere <= 0) continue;
      const moved = Math.min(spareHere, overloaded.overflowMinutes);
      suggestions.push({ fromDate: overloaded.date, toDate: days[i]!.date, minutes: moved });
      spare[i]! -= moved;
      break;
    }
  }

  return {
    days,
    overloadedDays,
    suggestions,
    totalPlannedMinutes: days.reduce((sum, d) => sum + d.plannedMinutes, 0),
    totalBaselineMinutes: days.reduce((sum, d) => sum + d.baselineMinutes, 0),
  };
}
