// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/screentime/series.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * The weekly screen-time series (D51).
 *
 * Self-reported by screenshot, because iOS does not expose Screen Time to third-party apps — and
 * better for it: the upload is the intervention, the number is only the record.
 *
 * The rule this module exists to hold: **a missed week is a gap, not a broken streak.** There is no
 * consecutive-week counter here, and `WeekPoint.minutes` is nullable so a chart renders a hole
 * rather than interpolating across one or dropping the week entirely. That is D23/D29/D30's ruling
 * reaching its fourth surface, and it is the fourth place it would have been easy to slip a streak
 * back in.
 */

import type { LocalDate } from '../types.ts';
import { addDays, compareLocalDate } from '../util/date.ts';

export interface ConfirmedWeek {
  weekStartDate: LocalDate;
  dailyAverageMinutes: number;
  breakdown: Record<string, number>;
}

export interface WeekPoint {
  weekStartDate: LocalDate;
  /** Null for a week with no confirmed upload. A hole, never a zero. */
  minutes: number | null;
}

/**
 * The last `weeks` weeks, oldest first, with gaps preserved.
 *
 * A zero would say "you used your phone for zero minutes that week", which is a claim; null says
 * "you did not report that week", which is the truth. Every chart reading this must render the
 * difference.
 */
export function buildSeries(
  confirmed: ConfirmedWeek[],
  currentWeekStart: LocalDate,
  weeks = 12,
): WeekPoint[] {
  const byWeek = new Map(confirmed.map((c) => [c.weekStartDate, c.dailyAverageMinutes]));
  const points: WeekPoint[] = [];
  for (let i = weeks - 1; i >= 0; i -= 1) {
    const weekStartDate = addDays(currentWeekStart, -7 * i);
    points.push({ weekStartDate, minutes: byWeek.get(weekStartDate) ?? null });
  }
  return points;
}

export interface SeriesSummary {
  /** Weeks actually reported in the window. */
  reportedWeeks: number;
  totalWeeks: number;
  /** Mean daily average across reported weeks only. Null when nothing was reported. */
  averageMinutes: number | null;
  /**
   * Change from the previous reported week to the most recent one, in minutes.
   *
   * Null unless there are TWO reported weeks — and deliberately compares the two most recent
   * REPORTED weeks rather than the two most recent calendar weeks, because comparing against a gap
   * would either invent a zero or silently report a change across an arbitrary span.
   */
  deltaMinutes: number | null;
  latest: WeekPoint | null;
}

export function summariseSeries(points: WeekPoint[]): SeriesSummary {
  const reported = points.filter((p): p is WeekPoint & { minutes: number } => p.minutes !== null);

  const latest = points.length > 0 ? points[points.length - 1]! : null;
  const lastTwo = reported.slice(-2);

  return {
    reportedWeeks: reported.length,
    totalWeeks: points.length,
    averageMinutes:
      reported.length === 0
        ? null
        : Math.round(reported.reduce((sum, p) => sum + p.minutes, 0) / reported.length),
    deltaMinutes: lastTwo.length < 2 ? null : lastTwo[1]!.minutes - lastTwo[0]!.minutes,
    latest,
  };
}

/**
 * Whether this week's screenshot is still owed.
 *
 * Used by the Sunday review to offer the step, never to nag: the answer is a fact the surface
 * renders as an invitation. A week that was never uploaded stays owed forever without escalating,
 * because there is nothing to escalate to — the series just has a hole.
 */
export function isWeekOutstanding(confirmed: ConfirmedWeek[], weekStart: LocalDate): boolean {
  return !confirmed.some((c) => c.weekStartDate === weekStart);
}

export interface StagedValue {
  label: string | null;
  minutes: number | null;
  needsInput: boolean;
}

/**
 * Whether a staged upload can be confirmed as it stands.
 *
 * The no-guessing rule at the confirm boundary: any row the model could not read must be filled by
 * a person first. This returns the fields still needing input rather than a boolean, so the surface
 * can point at them instead of refusing with a message.
 */
export function unresolvedFields(staged: StagedValue[]): StagedValue[] {
  return staged.filter((s) => s.needsInput || s.minutes === null);
}

/**
 * The Focus-dimension drift input.
 *
 * Returns a signal only on a real, sustained rise against the user's own recent baseline — never
 * against an external norm, because there is no defensible number of minutes a person should spend
 * on a phone and the app has no business implying one.
 *
 * Null when there is too little history to say, which is most of the time at first. Requiring four
 * reported weeks is deliberate: two weeks is noise, and a confrontation fired off noise would spend
 * the mechanic's credibility on nothing.
 */
export function screenTimeDriftSignal(points: WeekPoint[]): { risePercent: number } | null {
  const reported = points.filter((p): p is WeekPoint & { minutes: number } => p.minutes !== null);
  if (reported.length < 4) return null;

  const latest = reported[reported.length - 1]!.minutes;
  const priorWeeks = reported.slice(0, -1);
  const baseline = priorWeeks.reduce((sum, p) => sum + p.minutes, 0) / priorWeeks.length;
  if (baseline <= 0) return null;

  const risePercent = (latest - baseline) / baseline;
  // A quarter above the user's own baseline. Below that is a busy week.
  return risePercent >= 0.25 ? { risePercent } : null;
}
