// GENERATED by scripts/build-core-for-deno.mjs from packages/core/src/fitness/fitness.ts -- do not edit directly.
// Regenerate with `npm run build:core-for-deno` after any packages/core change.

/**
 * Fitness domain logic: 4-week cycles and weekly volume per muscle group.
 *
 * Ported from LifeOS (`lib/fitness/cycle.ts`, `volume.ts`). Both were already pure functions over
 * stored values rather than stored state of their own, which is the same argument migration 42
 * makes for the spaced-repetition scheduler: a derived cycle cannot drift from its anchor, and
 * nothing needs a cron to roll it over at midnight.
 *
 * The volume model's numbers are his spec's, not re-derived here: a movement credits its primary
 * mover one set and each secondary half a set (the fractional crediting that best predicted both
 * hypertrophy and strength in the 2025 dose-response meta-regression). His ruling that a muscle
 * listed as BOTH primary and secondary for one movement credits 1.0 rather than 1.5 is kept -- it
 * is one movement, the primary classification wins, and the duplicate listing is ignored rather
 * than added.
 */

import type { LocalDate } from '../types.ts';
import { addDays, compareLocalDate, daysBetween, isValidLocalDate } from '../util/date.ts';

export const CYCLE_LENGTH_DAYS = 28;

export type MuscleGroup =
  | 'chest'
  | 'back_lats'
  | 'back_mid'
  | 'front_delt'
  | 'side_delt'
  | 'rear_delt'
  | 'biceps'
  | 'triceps'
  | 'quads'
  | 'hamstrings'
  | 'glutes'
  | 'calves'
  | 'core';

export const MUSCLE_GROUPS: readonly MuscleGroup[] = [
  'chest',
  'back_lats',
  'back_mid',
  'front_delt',
  'side_delt',
  'rear_delt',
  'biceps',
  'triceps',
  'quads',
  'hamstrings',
  'glutes',
  'calves',
  'core',
] as const;

export const MUSCLE_GROUP_LABELS: Readonly<Record<MuscleGroup, string>> = {
  chest: 'Chest',
  back_lats: 'Lats',
  back_mid: 'Mid back',
  front_delt: 'Front delt',
  side_delt: 'Side delt',
  rear_delt: 'Rear delt',
  biceps: 'Biceps',
  triceps: 'Triceps',
  quads: 'Quads',
  hamstrings: 'Hamstrings',
  glutes: 'Glutes',
  calves: 'Calves',
  core: 'Core',
};

export interface Cycle {
  /** 1-indexed. */
  cycleNumber: number;
  startDate: LocalDate;
  /** Inclusive -- the cycle's last day. */
  endDate: LocalDate;
  /** Inclusive of `date` itself. */
  daysLeft: number;
  /** 1-indexed day within the cycle. */
  dayOfCycle: number;
}

/**
 * Which 4-week cycle a date falls in, given the user's stored anchor.
 *
 * All arithmetic runs on calendar-date strings, so this is DST-safe by construction: there is no
 * timezone lookup anywhere in it to get wrong.
 *
 * A date before the anchor clamps to cycle 1 day 1 rather than producing a negative cycle number,
 * and a malformed anchor degrades to a safe result instead of throwing into the caller -- this
 * renders a header, and a crash there would take down the whole Fitness page over a bad date.
 */
export function cycleForDate(anchorDate: string, date: LocalDate): Cycle {
  const safeAnchor: LocalDate = isValidLocalDate(anchorDate) ? anchorDate : '1970-01-01';
  const safeDate: LocalDate = isValidLocalDate(date) ? date : safeAnchor;

  const rawOffset = daysBetween(safeAnchor, safeDate);
  const offset = Math.max(0, rawOffset);

  const cycleIndex = Math.floor(offset / CYCLE_LENGTH_DAYS);
  const startDate = addDays(safeAnchor, cycleIndex * CYCLE_LENGTH_DAYS);
  const endDate = addDays(startDate, CYCLE_LENGTH_DAYS - 1);
  const dayOfCycle = (offset % CYCLE_LENGTH_DAYS) + 1;

  return {
    cycleNumber: cycleIndex + 1,
    startDate,
    endDate,
    daysLeft: CYCLE_LENGTH_DAYS - dayOfCycle + 1,
    dayOfCycle,
  };
}

/** True on the last day of a cycle -- where his spec places a benchmark. */
export function isCycleBoundary(anchorDate: string, date: LocalDate): boolean {
  return cycleForDate(anchorDate, date).dayOfCycle === CYCLE_LENGTH_DAYS;
}

export interface SetLike {
  exerciseId: number;
  reps: number | null;
}

export interface ExerciseMuscles {
  id: number;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles: MuscleGroup[];
}

/**
 * Fractional set credit per muscle group across a collection of performed sets.
 *
 * A set with null reps still counts as a set: it was performed, and the rep count simply was not
 * recorded. Dropping it would make an incompletely-logged session look like a rest day.
 */
export function volumeByMuscle(
  sets: SetLike[],
  exercises: ExerciseMuscles[],
): Record<MuscleGroup, number> {
  const byId = new Map<number, ExerciseMuscles>();
  for (const exercise of exercises) byId.set(exercise.id, exercise);

  const totals = Object.fromEntries(MUSCLE_GROUPS.map((m) => [m, 0])) as Record<MuscleGroup, number>;

  for (const set of sets) {
    const exercise = byId.get(set.exerciseId);
    if (!exercise) continue;

    const primary = new Set(exercise.primaryMuscles);
    for (const muscle of primary) totals[muscle] += 1;
    for (const muscle of exercise.secondaryMuscles) {
      // One movement: a muscle already credited as primary is not credited again.
      if (primary.has(muscle)) continue;
      totals[muscle] += 0.5;
    }
  }

  return totals;
}

export interface WeekDay {
  date: LocalDate;
  /** Sets confirmed on this day. Null when the day is in the future -- not zero. */
  confirmedSets: number | null;
}

/**
 * The Sun..Sat strip LifeOS shows on the Fitness page.
 *
 * A future day carries `null`, never `0`. A zero on Thursday when it is Tuesday is a claim that
 * Thursday was a rest day, which is a measurement of something that has not happened (D40, and the
 * same real-zero-is-not-absent rule the rest of the engine follows).
 */
export function weekStrip(
  weekStart: LocalDate,
  today: LocalDate,
  confirmedSetsByDate: Record<LocalDate, number>,
): WeekDay[] {
  const days: WeekDay[] = [];
  for (let i = 0; i < 7; i += 1) {
    const date = addDays(weekStart, i);
    const isFuture = compareLocalDate(date, today) > 0;
    days.push({ date, confirmedSets: isFuture ? null : (confirmedSetsByDate[date] ?? 0) });
  }
  return days;
}

export interface CycleProgress {
  /** Earliest recorded measurement in the cycle, if any. */
  first: { date: LocalDate; weightLb: number | null; waistIn: number | null } | null;
  latest: { date: LocalDate; weightLb: number | null; waistIn: number | null } | null;
  /** Latest minus first. Null unless BOTH ends of the comparison exist. */
  weightDeltaLb: number | null;
  waistDeltaIn: number | null;
}

/**
 * Body-composition change across a cycle.
 *
 * A delta needs two real measurements. One reading produces a null delta rather than a zero,
 * because "no change" and "nothing to compare" are different facts and only one of them is a
 * result.
 */
export function cycleProgress(
  measurements: { date: LocalDate; weightLb: number | null; waistIn: number | null }[],
  cycle: Cycle,
): CycleProgress {
  const inCycle = measurements
    .filter(
      (m) =>
        compareLocalDate(m.date, cycle.startDate) >= 0 && compareLocalDate(m.date, cycle.endDate) <= 0,
    )
    .sort((a, b) => compareLocalDate(a.date, b.date));

  if (inCycle.length === 0) {
    return { first: null, latest: null, weightDeltaLb: null, waistDeltaIn: null };
  }

  const first = inCycle[0]!;
  const latest = inCycle[inCycle.length - 1]!;

  const weightPair = [first.weightLb, latest.weightLb];
  const waistPair = [first.waistIn, latest.waistIn];

  return {
    first,
    latest,
    weightDeltaLb:
      weightPair.every((v) => v != null) && inCycle.length > 1
        ? Number((latest.weightLb! - first.weightLb!).toFixed(2))
        : null,
    waistDeltaIn:
      waistPair.every((v) => v != null) && inCycle.length > 1
        ? Number((latest.waistIn! - first.waistIn!).toFixed(2))
        : null,
  };
}
